"""The portion registry: which builders belong to whom.

This is the ONE shared file in this package, and it is deliberately tiny. Adding
a portion is one import line and one `Portion(...)` entry, so four people
touching it produce a three-line conflict at worst rather than a three-way merge
of a 700-line module.

A **portion** is one person's slice of cuet.ac.bd. It names the builders that
produce its documents, the output sections those documents land in, and the
parts of the live site they correspond to. `--portion <name>` runs one slice and
writes one shard, so nobody ever overwrites anybody else's output.

Sections may be shared between portions (`notices` writes an academic-calendar
index into `academic/notices/`), but the FILES never collide: every document is
named from its own id. Only the merged corpus files are shared, and those are
generated by `--stage merge`, never edited or committed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from . import academic, general, news, notices

__all__ = ["Portion", "PORTIONS", "builders_for", "portion_names"]


@dataclass(frozen=True)
class Portion:
    """One person's slice of the site.

    `sections` is documentation and audit, not enforcement — a builder is free
    to write elsewhere, and `build_notices` legitimately does. It exists so that
    `--stage audit` can report when a portion started writing somewhere nobody
    expected, which is the cheap way to notice two people colliding.
    """

    name: str
    owner: str
    builders: tuple[Callable, ...]
    sections: tuple[str, ...]
    site_areas: tuple[str, ...]


# Owner is a name, not a placeholder. An unowned portion is one nobody is
# checking, which is how a whole content type goes missing quietly.
PORTIONS: tuple[Portion, ...] = (
    Portion(
        name="general",
        owner="UNASSIGNED",
        builders=(general.build_cms, general.build_student_organizations),
        sections=("_cms", "home"),
        site_areas=("About menu", "Campus life", "Prospective students",
                    "Research highlights", "Student Organizations"),
    ),
    Portion(
        name="academic",
        owner="UNASSIGNED",
        builders=(academic.build_entities, academic.build_curricula),
        sections=("academic",),
        site_areas=("Academic menu", "/departments", "/faculty",
                    "/institutes", "/centers", "Curricula"),
    ),
    Portion(
        name="news-events",
        owner="UNASSIGNED",
        builders=(news.build_news, news.build_events),
        sections=("news-events",),
        site_areas=("News & Events menu", "/news/<id>", "/event-details/<id>"),
    ),
    Portion(
        name="notices",
        owner="UNASSIGNED",
        builders=(notices.build_notices,),
        sections=("top-bar", "admission", "academic", "_unsorted"),
        site_areas=("Notices menu", "Top-bar notice links",
                    "/notices/noc", "/notices/all-notice"),
    ),
)


def portion_names() -> tuple[str, ...]:
    return tuple(p.name for p in PORTIONS)


def builders_for(names: list[str] | None) -> tuple[Callable, ...]:
    """The builders to run, in registry order. `None` means every portion.

    Registry order rather than the caller's order, so that a run of two portions
    produces the same shard contents whichever way round they were named.
    """
    selected = PORTIONS if not names else tuple(
        p for p in PORTIONS if p.name in set(names)
    )
    return tuple(b for p in selected for b in p.builders)
